#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if any staged files contain .env*
# env_files=$(git diff --cached --name-only | grep .env*)
# if [ -n "$env_files" ]; then
#   echo "Error: Cannot commit .env files"
#   exit 1
# fi

pnpm lint-staged
